# Generated by Django 3.2.16 on 2023-03-04 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_project_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='auth_user.customuser'),
        ),
    ]
