# Generated by Django 3.2.16 on 2023-03-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserresume',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
