# Generated by Django 3.2.16 on 2023-03-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_customuserresume_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserresume',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuserresume',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ResumeStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_item', models.CharField(choices=[('Python', 'python'), ('C', 'c'), ('Scala', 'scala'), ('C++', 'cplusplus'), ('C#', 'csharp'), ('Java', 'java'), ('JavaScript', 'javascript'), ('Ruby', 'ruby'), ('PHP', 'php'), ('Django', 'django'), ('Flask', 'flask'), ('FastAPI', 'fastapi'), ('Laravel', 'laravel'), ('Symfony', 'symfony'), ('Spring', 'spring'), ('.NET', 'net'), ('React', 'react'), ('Angular', 'angular'), ('Ruby on rails', 'ruby on rails'), ('TypeScript', 'typescript'), ('MySQL', 'mysql'), ('PostgreSQL', 'postgresql'), ('Celery', 'celery')], max_length=16)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='auth_user.customuserresume')),
            ],
        ),
    ]
