# Generated by Django 3.2.16 on 2023-03-04 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos')),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('linked_in', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_item', models.CharField(choices=[('Python', 'python'), ('C', 'c'), ('Scala', 'scala'), ('C++', 'cplus'), ('C#', 'csharp'), ('Java', 'java'), ('JavaScript', 'javascript'), ('Ruby', 'ruby'), ('PHP', 'php'), ('Django', 'django'), ('Flask', 'flask'), ('FastAPI', 'fastapi'), ('Laravel', 'laravel'), ('Symfony', 'symfony'), ('Spring', 'spring'), ('.NET', 'net'), ('React', 'react'), ('Angular', 'angular'), ('Ruby on rails', 'ruby on rails'), ('TypeScript', 'typescript'), ('MySQL', 'mysql'), ('PostgreSQL', 'postgresql'), ('Celery', 'celery')], max_length=16)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='users.customuserresume')),
            ],
        ),
    ]
