# Generated by Django 3.2.16 on 2023-03-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumestack',
            name='project',
            field=models.ManyToManyField(related_name='project_stack', to='projects.Project'),
        ),
        migrations.RemoveField(
            model_name='resumestack',
            name='resume',
        ),
        migrations.AddField(
            model_name='resumestack',
            name='resume',
            field=models.ManyToManyField(related_name='tech_stack', to='users.CustomUserResume'),
        ),
        migrations.AlterField(
            model_name='resumestack',
            name='stack_item',
            field=models.CharField(choices=[('Python', 'python'), ('C', 'c'), ('Scala', 'scala'), ('C++', 'cplus'), ('C#', 'csharp'), ('Java', 'java'), ('JavaScript', 'javascript'), ('Ruby', 'ruby'), ('PHP', 'php'), ('Django', 'django'), ('Flask', 'flask'), ('FastAPI', 'fastapi'), ('Laravel', 'laravel'), ('Symfony', 'symfony'), ('Spring', 'spring'), ('.NET', 'net'), ('React', 'react'), ('Angular', 'angular'), ('Ruby on rails', 'ruby on rails'), ('TypeScript', 'typescript'), ('MySQL', 'mysql'), ('PostgreSQL', 'postgresql'), ('Celery', 'celery')], max_length=16, unique=True),
        ),
    ]
