# Generated by Django 3.2.16 on 2023-03-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0002_auto_20230304_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumestack',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project_stack', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='resumestack',
            name='resume',
            field=models.ManyToManyField(blank=True, related_name='tech_stack', to='users.CustomUserResume'),
        ),
    ]
